POST http://localhost:8080/auth/login
Content-Type: application/json

{
"userId": "test",
"password": "1234"
}

###

POST http://localhost:8080/auth/modify
Content-Type: application/json

{
  "userId": "test",
  "newPassword": "12345"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "userId": "test",
  "password": "12345"
}

### Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJ0ZXN0Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJpYXQiOjE3NDYwMjYxNjQsImV4cCI6MTc0NjAyODc1Nn0.llMXAxHQToRaCfTTn4NF_I6aWYPdJ1G8wBGhZC9kH04
### 아이디 test 비밀번호 1234 위 토큰으로 로그인